name: Java CI with Maven

on: [push, pull_request] # Kích hoạt khi có push hoặc pull request

jobs:
  build_and_test:
    runs-on: ubuntu-latest # Chạy trên máy ảo Ubuntu mới nhất
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Action để lấy code từ repo

    - name: Set up JDK 23 # Đã đổi tên bước và phiên bản JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23' # Thay đổi thành '23'
        distribution: 'temurin' 
        cache: 'maven'

    - name: Build and Test with Maven
      # Chạy lệnh build và test của Maven
      run: mvn -B package --file pom.xml test
      # '-B' : batch mode
      # 'package': build project (compile, test, package)
      # 'test': chạy các unit test
